//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Facility
    {
        public int FacilityId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string FacilityCode { get; set; }
        public string FacilityGroupCode { get; set; }
        public Nullable<int> FacilityOrder { get; set; }
        public Nullable<bool> IndYesOrNo { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<decimal> Distance { get; set; }
        public Nullable<bool> IndLogic { get; set; }
        public Nullable<bool> IndFee { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public string Currency { get; set; }
        public string ApplicationType { get; set; }
        public Nullable<System.TimeSpan> TimeFrom { get; set; }
        public Nullable<System.TimeSpan> TimeTo { get; set; }
        public string Voucher { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
