//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterestPoint
    {
        public int InterestPointId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string FacilityCode { get; set; }
        public string FacilityGroupCode { get; set; }
        public string POIName { get; set; }
        public Nullable<decimal> Distance { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
