//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomStay
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public RoomStay()
        {
            this.RoomStayFacilities = new HashSet<RoomStayFacility>();
        }
    
        public int RoomStayId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string StayType { get; set; }
        public Nullable<int> StayOrder { get; set; }
        public string Description { get; set; }
    
        public virtual Room Room { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomStayFacility> RoomStayFacilities { get; set; }
    }
}
