//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomFacility
    {
        public int RoomFacilityId { get; set; }
        public Nullable<int> RoomId { get; set; }
        public string FacilityCode { get; set; }
        public string FacilityGroupCode { get; set; }
        public Nullable<int> Number { get; set; }
        public Nullable<bool> IndLogic { get; set; }
        public Nullable<bool> IndYesOrNo { get; set; }
        public string Voucher { get; set; }
    
        public virtual Room Room { get; set; }
    }
}
