//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaskSolving.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terminal
    {
        public int TerminalId { get; set; }
        public Nullable<int> HotelId { get; set; }
        public string TerminalCode { get; set; }
        public Nullable<decimal> Distance { get; set; }
    
        public virtual Hotel Hotel { get; set; }
    }
}
